name: 'Trigger_TF_Per_Environment'
on:
  # workflow_dispatch:
  #   inputs:
  #     environments:
  #       description: 'Environment to deploy: dev, pre or pro'
  #       type: choice  
  #       options:
  #       - dev
  #       - pre
  #       - pro
    pull_request:
      branches:
        - main
      paths:
        - 'IaC/terraform/dev/**'
        - 'IaC/terraform/pre/**'
        - 'IaC/terraform/pro/**'

jobs:

  Path_filter:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          path_dev:
            - 'IaC/terraform/dev/**'
          path_pre:
            - 'IaC/terraform/pre/**'
          path_pro:
            - 'IaC/terraform/pro/**'
    outputs:
      path_dev: ${{ steps.filter.outputs.path_dev }}
      path_pre: ${{ steps.filter.outputs.path_pre }}
      path_pro: ${{ steps.filter.outputs.path_pro }} 

  Plan_Dev:
    # if: "${{ github.event.inputs.environments == 'dev' }}"
    needs: Path_filter
    if: ${{ github.event_name == 'pull_request' && needs.Path_filter.outputs.path_dev == 'true' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: dev
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Dev:
    needs: Plan_Dev
    if: ${{ github.event_name == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: dev
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Plan_Pre:
    # if: "${{ github.event.inputs.environments == 'pre' }}"
    needs: Path_filter
    if: ${{ github.event_name == 'pull_request' && needs.Path_filter.outputs.path_pre == 'true' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: pre
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Pre:
    needs: Plan_Pre
    if: ${{ github.event_name == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: pre
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Plan_Pro:
    # if: "${{ github.event.inputs.environments == 'pro' }}"
    needs: Path_filter
    if: ${{ github.event_name == 'pull_request' && needs.Path_filter.outputs.path_pro == 'true' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: pro
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Prod:
    needs: Plan_Pro
    if: ${{ github.event_name == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: pro
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}
