### Reusable workflow to download terraform artifact built by `az_tf_plan` and apply the artifact/plan ###
name: 'Apply_TF_Plan'
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment prefix to deploy into'
        required: true
        type: string
    secrets:
      DEV_CREDENTIALS: 
        description: 'Specifies the Azure DEV CREDS.'
        required: true
      PRE_CREDENTIALS: 
        description: 'Specifies the Azure PRE CREDS.'
        required: true
      PRO_CREDENTIALS:
        description: 'Specifies the Azure PRO CREDS.'
        required: true
        
env:
  STORAGE_ACCOUNT: iacsa${{ inputs.environment }}
  CONTAINER_NAME: tfstate
  RESOURCE_GROUP: IaC-Deployment-RG-${{ inputs.environment }}
  TF_KEY: terraform.${{ inputs.environment }}.tfstate
  TF_VARS: env.${{ inputs.environment }}.tfvars
  ROOT_TERRAFORM_MODULE: 'IaC/terraform'
  ###AZURE Client details###
  DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
  PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
  PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

jobs:
  login-to-azure:
    runs-on: ubuntu-latest
    steps:
      -name: Login to azure
        run: |
          az login --service-principal --username ${{ secrets.DEV_CLIENT_ID }} --password ${{ secrets.DEV_CLIENT_SECRET }} --tenant ${{ secrets.DEV_TENANT_ID }} || { echo "::error::Error login into Azure. Most likely there is NOT a SECRET AVAILABLE for your environment that contains your Azure credentials."; exit 199; }
          az account set --subscription ${{ secrets.DEV_SUBSCRIPTION_ID }} || { echo "::error::Error setting subscriptcion. Provide a correct subscription. Verify your Azure credentials."; exit 199; }
 
  apply-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.ROOT_TERRAFORM_MODULE }}

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.TF_KEY }}
          path: ${{ env.ROOT_TERRAFORM_MODULE }}

      - name: Decompress TF Plan artifact
        run: unzip ${{ env.TF_KEY }}.zip

      - name: Terraform Init
        id: init
        run: terraform init -migrate-state --backend-config="storage_account_name=$STORAGE_ACCOUNT" --backend-config="container_name=$CONTAINER_NAME" --backend-config="resource_group_name=$RESOURCE_GROUP" --backend-config="key=$TF_KEY"

      - name: Terraform Apply
        run: terraform apply plan.tfplan
