name: 'Trigger_TF_Per_Environment'
on:
  # workflow_dispatch:
  #   inputs:
  #     environments:
  #       description: 'Environment to deploy: dev, pre or pro'
  #       type: choice  
  #       options:
  #       - dev
  #       - pre
  #       - pro
    pull_request:
      branches:
        - main
      paths:
        - 'IaC/terraform/dev/**'
        - 'IaC/terraform/pre/**'
        - 'IaC/terraform/pro/**'

jobs:
  Plan_Dev:
    # if: "${{ github.event.inputs.environments == 'dev' }}"
    if: ${{ github.event_name == 'pull_request' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: dev
      trigger_event: ${{ github.event_name }}
      # env_path: 'IaC/terraform/dev/**'
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Dev:
    needs: Plan_Dev
    if: ${{ github.event_name == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: dev
      trigger_event: ${{ github.event_name }}
      # env_path: 'IaC/terraform/dev/**'
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Plan_Pre:
    # if: "${{ github.event.inputs.environments == 'pre' }}"
    if: ${{ github.event_name == 'pull_request' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: pre
      trigger_event: ${{ github.event_name }}
      # env_path: 'IaC/terraform/pre/**'
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Pre:
    needs: Plan_Pre
    if: ${{ github.event_name == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: pre
      trigger_event: ${{ github.event_name }}
      # env_path: 'IaC/terraform/pre/**'
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Plan_Pro:
    # if: "${{ github.event.inputs.environments == 'pro' }}"
    if: ${{ github.event_name == 'pull_request' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: pro
      trigger_event: ${{ github.event_name }}
      # env_path: 'IaC/terraform/pro/**'
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Prod:
    needs: Plan_Pro
    if: ${{ github.event_name == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: pro
      trigger_event: ${{ github.event_name }}
      # env_path: 'IaC/terraform/pro/**'
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}
