name: 'Build_TF_Plan'
on:
  workflow_call:
    inputs:
      environments:
        description: 'Environment prefix to deploy into'
        required: true
        type: string
      trigger_event:
        description: 'Trigger event for workflow'
        required: true
        type: string
      # env_path:
      #   description: 'Environment path'
      #   required: true
      #   type: string
    secrets:
      DEV_CREDENTIALS: 
        description: 'Specifies the Azure DEV CREDS.'
        required: true
      PRE_CREDENTIALS: 
        description: 'Specifies the Azure PRE CREDS.'
        required: true
      PRO_CREDENTIALS:
        description: 'Specifies the Azure PRO CREDS.'
        required: true
        
env:
  RESOURCE_GROUP: IaC-Deployment-RG-${{ inputs.environments }}
  STORAGE_ACCOUNT: iacsa${{ inputs.environments }}
  CONTAINER_NAME: tfstateiac
  TF_KEY: terraform.${{ inputs.environments }}.tfstate
  TF_VARS: ${{ inputs.environments }}.tfvars
  ROOT_TERRAFORM_MODULE: 'IaC/terraform/${{ inputs.environments }}'
  ###AZURE Client details###
  DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
  PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
  PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

jobs: 
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.ROOT_TERRAFORM_MODULE }}
        
    steps:        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
      
      - name: Az Login
        run:
          az login --allow-no-subscriptions

      - name: Terraform Init
        id: init
        run: 
          terraform init -migrate-state --backend-config="storage_account_name=$STORAGE_ACCOUNT" --backend-config="container_name=$CONTAINER_NAME" --backend-config="resource_group_name=$RESOURCE_GROUP" --backend-config="key=$TF_KEY"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan --var-file=$TF_VARS --out=plan.tfplan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Compress TF Plan artifact
        run: zip -r ${{ env.TF_KEY }}.zip ./*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.TF_KEY }}'
          path: '${{ env.ROOT_TERRAFORM_MODULE }}/${{ env.TF_KEY }}.zip'
          retention-days: 5