name: 'Trigger_TF_Per_Environment'
on:
  # workflow_dispatch:
  #   inputs:
  #     environments:
  #       description: 'Environment to deploy: dev, pre or pro'
  #       type: choice  
  #       options:
  #       - dev
  #       - pre
  #       - pro
    pull_request:
      branches:
        - main
      paths:
        - 'IaC/terraform/dev/**'
        - 'IaC/terraform/pre/**'
        - 'IaC/terraform/pro/**'

jobs:
  filter_path:
    if: ${{ github.event_name == 'pull_request' }}
    uses: Cairimia/IaC_deployment/.github/workflows/filter_path.yaml@main
    # with:
    #   trigger_event: ${{ github.event_name }}
    # secrets:
    #   DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
    #   PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
    #   PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Plan_Dev:
    # if: "${{ github.event.inputs.environments == 'dev' }}"
    needs: filter_path
    if: ${{ inputs.trigger_event == 'pull_request' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: dev
      trigger_event: ${{ github.event_name }}
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Dev:
    needs: [Plan_Dev, filter_path]
    if: ${{ inputs.trigger_event == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: dev
      trigger_event: ${{ github.event_name }}
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Plan_Pre:
    # if: "${{ github.event.inputs.environments == 'pre' }}"
    needs: filter_path
    if: ${{ inputs.trigger_event == 'pull_request' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: pre
      trigger_event: ${{ github.event_name }}
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Pre:
    needs: [Plan_Pre, filter_path]
    if: ${{ inputs.trigger_event == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: pre
      trigger_event: ${{ github.event_name }}
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Plan_Pro:
    # if: "${{ github.event.inputs.environments == 'pro' }}"
    needs: filter_path
    if: ${{ inputs.trigger_event == 'pull_request' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@main
    with:
      environments: pro
      trigger_event: ${{ github.event_name }}
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}

  Deploy_Prod:
    needs: [Plan_Pro, filter_path]
    if: ${{ inputs.trigger_event == 'push' }}
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@main
    with:
      environments: pro
      trigger_event: ${{ github.event_name }}
    secrets:
      DEV_CREDENTIALS: ${{ secrets.DEV_CREDENTIALS }}
      PRE_CREDENTIALS: ${{ secrets.PRE_CREDENTIALS }}
      PRO_CREDENTIALS: ${{ secrets.PRO_CREDENTIALS }}