name: 'Build_TF_Plan'
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment prefix to deploy into'
        required: true
        type: string
    secrets:
      DEV_DEV_CLIENT_ID: 
        description: "caa9a127-ff19-4a5d-986e-399405412731",
      DEV_CLIENT_SECRET: 
        description: "48294428-ab48-4973-abc7-d0c6c5a6a1dd"
      DEV_SUBSCRIPTION_ID:
        description: "9b3bd631-0b3e-44ca-9ee5-1e3cd8ab9652"
      DEV_TENANT_ID: 
        description: "9lVPr1z4hP9a9ahumAr37SM9Ugmcoww4bkcL9tI1PVs="
        
env:
  STORAGE_ACCOUNT: iacsa${{ inputs.environment }}
  CONTAINER_NAME: tfstate
  RESOURCE_GROUP: IaC-Deployment-RG-${{ inputs.environment }}
  TF_KEY: terraform.${{ inputs.environment }}.tfstate
  TF_VARS: env.${{ inputs.environment }}.tfvars
  ROOT_TERRAFORM_MODULE: 'IaC/terraform'
  ###AZURE Client details###
  DEV_DEV_CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
  DEV_CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
  DEV_SUBSCRIPTION_ID: ${{ secrets.DEV_SUBSCRIPTION_ID }}
  DEV_TENANT_ID: ${{ secrets.DEV_TENANT_ID }}

jobs:
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.ROOT_TERRAFORM_MODULE }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Terraform Init
        id: init
        run: terraform init -migrate-state --backend-config="storage_account_name=$STORAGE_ACCOUNT" --backend-config="container_name=$CONTAINER_NAME" --backend-config="resource_group_name=$RESOURCE_GROUP" --backend-config="key=$TF_KEY"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan --var-file=$TF_VARS --out=plan.tfplan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Compress TF Plan artifact
        run: zip -r ${{ env.TF_KEY }}.zip ./*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.TF_KEY }}'
          path: '${{ env.ROOT_TERRAFORM_MODULE }}/${{ env.TF_KEY }}.zip'
          retention-days: 5
