name: 'Filter_Path'
on:
  workflow_call:
    # inputs:
    #   trigger_event:
    #     description: 'Trigger event for workflow'
    #     required: true
    #     type: string
    # secrets:
    #   DEV_CREDENTIALS: 
    #     description: 'Specifies the Azure DEV CREDS.'
    #     required: true
    #   PRE_CREDENTIALS: 
    #     description: 'Specifies the Azure PRE CREDS.'
    #     required: true
    #   PRO_CREDENTIALS:
    #     description: 'Specifies the Azure PRO CREDS.'
    #     required: true

jobs:
  filter_path:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dev:
            - 'IaC/terraform/dev/**'
          pre:
            - 'IaC/terraform/pre/**'
          pro:
            - 'IaC/terraform/pro/**'
    outputs:
      dev: ${{ steps.filter.outputs.dev }}
      pre: ${{ steps.filter.outputs.pre }}
      pro: ${{ steps.filter.outputs.pro }}