name: 'Filter_Path'
on:
  workflow_call:
    # inputs:
    #   trigger_event:
    #     description: 'Trigger event for workflow'
    #     required: true
    #     type: string
    # secrets:
    #   DEV_CREDENTIALS: 
    #     description: 'Specifies the Azure DEV CREDS.'
    #     required: true
    #   PRE_CREDENTIALS: 
    #     description: 'Specifies the Azure PRE CREDS.'
    #     required: true
    #   PRO_CREDENTIALS:
    #     description: 'Specifies the Azure PRO CREDS.'
    #     required: true

jobs:
  filter_path:
    runs-on: ubuntu-latest
    outputs:
      dev_path: ${{ steps.filter.outputs.dev }}
      pre_path: ${{ steps.filter.outputs.pre }}
      pro_path: ${{ steps.filter.outputs.pro }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          dev:
            - 'IaC/terraform/dev/**'
          pre:
            - 'IaC/terraform/pre/**'
          pro:
            - 'IaC/terraform/pro/**'

  output_paths:
    runs-on: ubuntu-latest
    needs: filter_path
    steps:
      - run: echo ${{needs.filter_path.outputs.dev_path}} 
      - run: echo ${{needs.jfilter_path.outputs.pre_path}} 
      - run: echo ${{needs.jfilter_path.outputs.pro_path}}
