name: 'Trigger Deployment per Environment'
on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Environment to deploy: dev, pre or pro'
        type: choice  
        options:
        - dev
        - pre
        - pro

jobs:
  Plan_Dev:
    if: "${{ github.event.inputs.environments == 'dev' }}"
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@master
    with:
      environment: dev

  Deploy_Dev:
    needs: Plan_Dev
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@master
    with:
      environment: dev

  Plan_Pre:
    if: "${{ github.event.inputs.environments == 'pre' }}"
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@master
    with:
      environment: pre

  Deploy_Pre:
    needs: [Plan_Pre, Deploy_Dev]
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@master
    with:
      environment: pre

  Plan_Pro:
    if: "${{ github.event.inputs.environments == 'pro' }}"
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_plan.yml@master
    with:
      environment: pro

  Deploy_Prod:
    needs: [Plan_Pro, Deploy_Pre]
    uses: Cairimia/IaC_deployment/.github/workflows/az_tf_apply.yml@master
    with:
      environment: pro
env:
  TF_VARS_FILE: ${{ inputs.environment }}.tfvars.
  STORAGE_ACCOUNT: iacsa${{ inputs.environment }}
  CONTAINER_NAME: tfstate
  RESOURCE_GROUP: IaC-Deployment-RG-${{ inputs.environment }}
  TF_KEY: terraform${{ inputs.environment }}.tfstate
  TF_VARS: ${{ inputs.environment }}.tfvars
  ###AZURE Client details###
  DEV_DEPLOY_CREDS: ${{ secrets.DEV_CREDENTIALS }}
  PRE_DEPLOY_CREDS: ${{ secrets.PRE_CREDENTIALS }}
  PRO_DEPLOY_CREDS: ${{ secrets.PRO_CREDENTIALS }}
  ROOT_TERRAFORM_MODULE: 'IaC/terraform'
